version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: ./build/Dockerfile_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./apps/:/usr/src/apps/
    ports:
      - 9000:8000
    env_file:
      - ./build/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=baseuser
      - POSTGRES_PASSWORD=basepass
      - POSTGRES_DB=basepostgres

volumes:
  postgres_data:
