# Generated by Django 2.2.6 on 2020-05-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200523_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='garge',
            new_name='garage',
        ),
    ]
